databases:
  - name: social_db
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: social_book
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn social_book.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: social_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4